#Data Cleaning & Data preprocessing

In [3]:
import pandas as pd
df=pd.read_csv(r"C:\Users\My Lap\OneDrive\Desktop\Marketing_Campaign\marketing_campaign_data.csv")
df

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Response,Complain,Country
0,342199,1985,Graduation,Together,59011.7,1,0,11-17-2012,3,0,...,3,4,0,0,0,0,0,0,0,Spain
1,8075450,1975,Master,Single,1730.0,1,1,04-10-2013,96,0,...,2,3,0,0,0,0,0,0,0,Spain
2,13664263,1978,Graduation,Married,98584.6,0,0,01-11-2014,99,920,...,6,3,0,0,0,0,0,0,0,Australia
3,16164787,1976,Graduation,Married,74031.5,1,0,06-18-2014,47,265,...,11,4,0,0,0,0,0,0,0,Spain
4,15815139,1981,Graduation,Divorced,52784.2,1,1,05-20-2014,0,30,...,3,6,0,0,0,0,0,0,0,Canada
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55995,2485439,1985,Graduation,Married,32533.4,0,0,04-05-2013,99,8,...,6,8,0,0,0,0,0,0,0,Australia
55996,9202496,1992,Basic,Single,70496.3,0,1,01-31-2013,9,835,...,8,4,0,0,0,0,0,0,0,Germany
55997,14677746,1950,Graduation,Together,21072.0,1,0,06-25-2013,24,0,...,0,3,0,0,0,0,0,1,0,Saudi Arabia
55998,3843719,1976,Graduation,Together,64218.1,0,0,05-12-2014,81,8,...,1,8,0,0,0,0,0,0,0,Saudi Arabia
55999,3195751,1984,Graduation,Married,89322.8,0,1,09-04-2013,93,113,...,1,4,0,0,0,0,0,0,0,Saudi Arabia

In [4]:
df.isna().sum()

ID                     0
Year_Birth             0
Education              0
Marital_Status         0
Income                 0
Kidhome                0
Teenhome               0
Dt_Customer            0
Recency                0
MntWines               0
MntFruits              0
MntMeatProducts        0
MntFishProducts        0
MntSweetProducts       0
MntGoldProds           0
NumDealsPurchases      0
NumWebPurchases        0
NumCatalogPurchases    0
NumStorePurchases      0
NumWebVisitsMonth      0
AcceptedCmp3           0
AcceptedCmp4           0
AcceptedCmp5           0
AcceptedCmp1           0
AcceptedCmp2           0
Response               0
Complain               0
Country                0
dtype: int64

Convert Dt_Customer to date type and derive Customer_Tenure

In [5]:
df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'], errors='coerce')
reference_date = pd.to_datetime('2026-07-01')
df['Customer_Tenure_Days'] = (reference_date - df['Dt_Customer']).dt.days
df['Customer_Tenure_Months'] = (reference_date - df['Dt_Customer']).dt.days // 30
print(df[['Dt_Customer', 'Customer_Tenure_Days', 'Customer_Tenure_Months']].head())

  Dt_Customer  Customer_Tenure_Days  Customer_Tenure_Months
0  2012-11-17                  4974                     165
1  2013-04-10                  4830                     161
2  2014-01-11                  4554                     151
3  2014-06-18                  4396                     146
4  2014-05-20                  4425                     147

Age from Year_Birth

In [6]:
from datetime import datetime
#current_year = datetime.datetime.now().year
current_year = datetime.today().year

df['Age'] = current_year - df['Year_Birth']

print(df[['Year_Birth', 'Age']].head())

   Year_Birth  Age
0        1985   41
1        1975   51
2        1978   48
3        1976   50
4        1981   45

Total_Spend as sum of all Mnt* fields.

In [7]:
spend_columns = ['MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts', 'MntGoldProds']
df['Total_Spend'] = df[spend_columns].sum(axis=1)
print(df[spend_columns + ['Total_Spend']].head())

   MntWines  MntFruits  MntMeatProducts  MntFishProducts  MntSweetProducts  \
0         0          2               45                6                 0
1         0          0               19                1                19
2       920          0              339                0               115
3       265          0              130                7                 1
4        30          3               55              242                 0

   MntGoldProds  Total_Spend
0            16           69
1             0           39
2           138         1512
3            75          478
4             0          330

Total_Purchases as sum of channel purchases.

In [8]:
channel_columns = ['NumDealsPurchases', 'NumWebPurchases', 'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth']
df['Total_Purchases'] = df[channel_columns].sum(axis=1)
print(df[channel_columns + ['Total_Purchases']].head())

   NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  NumStorePurchases  \
0                  3                2                    5                  3
1                  1                1                    0                  2
2                  3                2                    1                  6
3                  1                4                    0                 11
4                  1                3                    2                  3

   NumWebVisitsMonth  Total_Purchases
0                  4               17
1                  3                7
2                  3               15
3                  4               20
4                  6               15

Childrens at home

In [9]:
children_columns = ['Kidhome', 'Teenhome']
df['Total_Children'] = df[children_columns].sum(axis=1) 
print(df[children_columns + ['Total_Children']].head())

   Kidhome  Teenhome  Total_Children
0        1         0               1
1        1         1               2
2        0         0               0
3        1         0               1
4        1         1               2

In [10]:
df

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,AcceptedCmp2,Response,Complain,Country,Customer_Tenure_Days,Customer_Tenure_Months,Age,Total_Spend,Total_Purchases,Total_Children
0,342199,1985,Graduation,Together,59011.7,1,0,2012-11-17,3,0,...,0,0,0,Spain,4974,165,41,69,17,1
1,8075450,1975,Master,Single,1730.0,1,1,2013-04-10,96,0,...,0,0,0,Spain,4830,161,51,39,7,2
2,13664263,1978,Graduation,Married,98584.6,0,0,2014-01-11,99,920,...,0,0,0,Australia,4554,151,48,1512,15,0
3,16164787,1976,Graduation,Married,74031.5,1,0,2014-06-18,47,265,...,0,0,0,Spain,4396,146,50,478,20,1
4,15815139,1981,Graduation,Divorced,52784.2,1,1,2014-05-20,0,30,...,0,0,0,Canada,4425,147,45,330,15,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55995,2485439,1985,Graduation,Married,32533.4,0,0,2013-04-05,99,8,...,0,0,0,Australia,4835,161,41,53,27,0
55996,9202496,1992,Basic,Single,70496.3,0,1,2013-01-31,9,835,...,0,0,0,Germany,4899,163,34,924,16,1
55997,14677746,1950,Graduation,Together,21072.0,1,0,2013-06-25,24,0,...,0,1,0,Saudi Arabia,4754,158,76,608,8,1
55998,3843719,1976,Graduation,Together,64218.1,0,0,2014-05-12,81,8,...,0,0,0,Saudi Arabia,4433,147,50,69,16,0
55999,3195751,1984,Graduation,Married,89322.8,0,1,2013-09-04,93,113,...,0,0,0,Saudi Arabia,4683,156,42,262,10,1

Outliers handling on Total_Spend

In [11]:
column_name = 'Total_Spend'

Q1 = df[column_name].quantile(0.25)
Q3 = df[column_name].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df[column_name] < lower_bound) | (df[column_name] > upper_bound)]

print(f"Lower limit for normal data: {lower_bound}")
print(f"Upper limit for normal data: {upper_bound}")
print(f"Number of outliers found: {len(outliers)}")

Lower limit for normal data: -1272.5
Upper limit for normal data: 2395.5
Number of outliers found: 705

In [29]:
df['Total_Spend'] = df['Total_Spend'].clip(lower=lower_bound, upper=upper_bound)

print("Outliers capped! Max spend is now:", df['Total_Spend'].max())

Outliers capped! Max spend is now: 2395.5

In [31]:
column_name = 'Age'

# 3. Calculate Q1 (25th percentile) and Q3 (75th percentile)
Q1 = df[column_name].quantile(0.25)
Q3 = df[column_name].quantile(0.75)
IQR = Q3 - Q1

# 4. Define the outlier boundaries
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# 5. Extract the outliers from the DataFrame
outliers = df[(df[column_name] < lower_bound) | (df[column_name] > upper_bound)]

print(f"Lower limit for normal data: {lower_bound}")
print(f"Upper limit for normal data: {upper_bound}")
print(f"Number of outliers found: {len(outliers)}")

Lower limit for normal data: 18.0
Upper limit for normal data: 90.0
Number of outliers found: 0

In [32]:
column_name = 'Income'

# 3. Calculate Q1 (25th percentile) and Q3 (75th percentile)
Q1 = df[column_name].quantile(0.25)
Q3 = df[column_name].quantile(0.75)
IQR = Q3 - Q1

# 4. Define the outlier boundaries
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# 5. Extract the outliers from the DataFrame
outliers = df[(df[column_name] < lower_bound) | (df[column_name] > upper_bound)]

print(f"Lower limit for normal data: {lower_bound}")
print(f"Upper limit for normal data: {upper_bound}")
print(f"Number of outliers found: {len(outliers)}")

Lower limit for normal data: -59765.912499999984
Upper limit for normal data: 174948.58749999997
Number of outliers found: 14

In [33]:
df['Income'] = df['Income'].clip(lower=lower_bound, upper=upper_bound)

print("Outliers capped! Max spend is now:", df['Income'].max())

Outliers capped! Max spend is now: 174948.58749999997

In [1]:
import matplotlib.pyplot as plt
import seaborn as sns

# Create a boxplot for total spend
sns.boxplot(x=df['Income'])
plt.title('Detecting Outliers in Total Spend')
plt.show()

NameError: name 'df' is not defined

In [34]:
df.to_csv('cleaned_data.csv', index=False)

In [38]:
import numpy as np
import pandas as pd

# 1. Load your dataset
df = pd.read_csv(r"C:\Users\My Lap\OneDrive\Desktop\Marketing_Campaign\cleaned_data.csv")

# 2. Calculate the 90th percentile threshold dynamically for High Spenders
high_spend_threshold = df["Total_Spend"].quantile(0.90)

# ==========================================
# Apply the exact text values based on rules
# ==========================================

# 1. High Income (Shows the range text or "Not High")
df["Segment_High_Income"] = np.where(df["Income"] > 75000, "75001–99999", "Normal Income")

# 2. Young Customer (Shows the age range text or "30+")
df["Segment_Young_Customer"] = np.where(df["Age"] < 30, "18–29", "30+")

# 3. Campaign Responder (Shows "1" or "0")
df["Segment_Campaign_Responder"] = np.where(df["Response"] == 1, "1", "0")

# 4. High Web Engagement (Shows the visit range text or "<=5")
df["Segment_High_Web_Engagement"] = np.where(df["NumWebVisitsMonth"] > 5, "6–20", "0–5")

# 5. Family Customer (Shows the children range text or "0")
df["Segment_Family_Customer"] = np.where(df["Total_Children"] > 0, "1–3", "0")

# 6. High Spender (Shows "> ₹50,000" or "Normal Spender")
df["Segment_High_Spender"] = np.where(df["Total_Spend"] > high_spend_threshold, f"> ₹{int(high_spend_threshold):,}", "Normal Spender")


# 3. Save the segmented data to a new CSV file
df.to_csv("segmented_data.csv", index=False)

# 4. Preview the results to verify the new text values
preview_cols = [col for col in df.columns if col.startswith("Segment_")]
print(df[preview_cols].head(10))

  Segment_High_Income Segment_Young_Customer Segment_Campaign_Responder  \
0       Normal Income                    30+                          0
1       Normal Income                    30+                          0
2         75001–99999                    30+                          0
3       Normal Income                    30+                          0
4       Normal Income                    30+                          0
5       Normal Income                    30+                          0
6         75001–99999                    30+                          0
7       Normal Income                    30+                          0
8       Normal Income                    30+                          0
9       Normal Income                    30+                          0

  Segment_High_Web_Engagement Segment_Family_Customer Segment_High_Spender
0                         0–5                     1–3       Normal Spender
1                         0–5                     1–3       Normal Spender
2                         0–5                       0       Normal Spender
3                         0–5                     1–3       Normal Spender
4                        6–20                     1–3       Normal Spender
5                         0–5                     1–3       Normal Spender
6                         0–5                       0       Normal Spender
7                         0–5                     1–3       Normal Spender
8                         0–5                     1–3       Normal Spender
9                         0–5                     1–3       Normal Spender